name: nasa_pictures_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get_it: ^7.6.4
  dio: ^5.3.2
  shared_preferences: ^2.2.1
  cached_network_image: ^3.2.3
  mocktail: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

