name: nasa_pictures_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get_it: ^9.2.1
  dio: ^5.9.2
  shared_preferences: ^2.5.4
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
  shared_preferences_platform_interface: ^2.4.1

flutter:
  uses-material-design: true

